-- return {
--   'karb94/neoscroll.nvim',
--   opts = {},
--   config = function()
--     neoscroll = require 'neoscroll'
--     neoscroll.setup {
--       -- Default easing function used in any animation where
--       -- the `easing` argument has not been explicitly supplied
--       easing = 'sine',
--     }
--     local keymap = {
--       -- Use the "sine" easing function
--       ['<C-u>'] = function()
--         neoscroll.ctrl_u { duration = 100 }
--       end,
--       ['<C-d>'] = function()
--         neoscroll.ctrl_d { duration = 100 }
--       end,
--       -- -- Use the "circular" easing function
--       -- ['<C-b>'] = function()
--       --   neoscroll.ctrl_b { duration = 450 }
--       -- end,
--       -- ['<C-f>'] = function()
--       --   neoscroll.ctrl_f { duration = 450 }
--       -- end,
--     }
--     local modes = { 'n', 'v', 'x' }
--     for key, func in pairs(keymap) do
--       vim.keymap.set(modes, key, func)
--     end
--   end,
-- }
